### PR TITLE
Replace examples with doc-example

### PR DESCRIPTION
**Pull request by berland**
With this PR the example is actually buildable.

### CODE REVIEW

**Comment by hnformentin** [comment]
Could you check the tests? They are failing in linting so far...

**Comment by berland** [comment]
> Could you check the tests? They are failing in linting so far...

yup, they need an update..

**Comment by berland** [comment]
> Could you check the tests? They are failing in linting so far...

Fixed!

**Review by hnformentin — APPROVED** [review]
LGTM!

**Pull request merged**
