### PR TITLE
Add time profiling

### PR DESCRIPTION
**Pull request by berland**

### CODE REVIEW

**Review by kwinkunks — COMMENTED** [review]
Wondering a bit if there are any patterns for this kind of thing that would avoid scattering the timing code through the business logic? It's not something I've ever looked at before; I guess it's a kind of logging. I don't know what to suggest but, for example, could we make a decorator for the various functions `fetch`, `make`, `shell` etc instead?

**Comment by berland** [comment]
Some hints might be taken from here: https://stackoverflow.com/questions/33987060/python-context-manager-that-measures-time

**Review by xjules — APPROVED** [review]
Nice! :rocket:

**Comment by berland** [comment]
Decided to merge it even if it is at a primitive stage for the sake of data gathering.

**Pull request merged**
