### PR TITLE
Ignore invalid versions/specifiers in pypi checker

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
As far as I understand, we pull all builds of a package from pypi, and then try to parse their version and python requirement. Some packages seem to have unparsable pre-release versions (absl-py: `1.3.0.dev-r634`), or invalid python specifiers (pyzmq: `!=3.0*`).

We ignore all types of such errors, presuming that they occur on builds that are irrelevant for us.

### CODE REVIEW

**Comment by DanSava** [comment]
> We ignore all types of such errors, presuming that they occur on builds that are irrelevant for us.

This sounds like a very strong assumption to make. Not saying it is wrong, just maybe double-check with somebody with a bit more experience with the komodo codebase.

**Comment by valentin-krasontovitsch** [comment]
i have requested @berland and @oyvindeide - hoping that one of them will be able to say if this is OK : )

**Comment by berland** [comment]
There is a linter in komodo that at least gives warnings for "dangerous" versions, I suppose these should be flagged like that as well.

**Comment by berland** [comment]
Getting there, thanks for the context. I think this looks good!

**Review by berland — APPROVED** [review]

**Pull request merged**
