### PR TITLE
Fetch ci_helper using git instead of wget

### PR DESCRIPTION
**Pull request by ManInFez**
Fixes failing wget to githubusers.com

### CODE REVIEW

**Comment by markusdregi** [comment]
Tested it locally and it seems to work 👍🏻 Perhaps this change deserves a comment in the script, the commit message body or both?

**Comment by ManInFez** [comment]
I think maybe we should wait to see if we get the network fixed

**Comment by ManInFez** [comment]
> Tested it locally and it seems to work 👍🏻 Perhaps this change deserves a comment in the script, the commit message body or both?

probably both

**Comment by sondreso** [comment]
I guess we can close this, as the network issues are gone?

**Pull request closed without merging**
